# Generated by Django 5.2.8 on 2026-01-27 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='fecha_expiracion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='tipo',
            field=models.CharField(choices=[('normal', 'Normal'), ('estudiante', 'Estudiante'), ('jubilado', 'Jubilado')], default='normal', max_length=20),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_conductor', models.BooleanField(default=False, verbose_name='Es Conductor')),
                ('chofer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='transporte.chofer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
                'db_table': 'user_profiles',
            },
        ),
    ]
