# Generated by Django 5.2.8 on 2026-01-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0002_tarjeta_fecha_expiracion_tarjeta_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_conductor',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_asistente',
            field=models.BooleanField(default=False, verbose_name='Es Asistente/Cobrador'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_chofer',
            field=models.BooleanField(default=False, verbose_name='Es Chofer'),
        ),
    ]
