# Generated by Django 4.2 on 2026-01-24 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transporte', '0002_tarjeta_fecha_expiracion_tarjeta_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to=settings.AUTH_USER_MODEL),
        ),
    ]
