# Generated by Django 4.2 on 2026-01-27 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0003_alter_tarjeta_usuario'),
    ]

    operations = [
    ]
