# Generated by Django 4.2 on 2026-01-27 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0003_remove_userprofile_is_conductor_and_more'),
        ('transporte', '0004_crear_user_profile'),
    ]

    operations = [
    ]
