# Generated by Django 4.2 on 2026-01-28 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0004_vehiculo_linea'),
        ('transporte', '0005_merge_20260127_0236'),
    ]

    operations = [
    ]
